name: api_client_utils
description: Classes for use in Dart API Clients.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.24.4
